import styles from "styles/Home.module.css";
import Head from "next/head";
import { useQuery, gql } from "@apollo/client";
import DividerSection from "components/DividerSection/DividerSection";
import Experience from "components/Experience/Experience";
import Header from "components/Header/Header";
import Main from "components/Main/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>林 :: Forest Park || Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex row-auto content-center items-center">
        <Main />
      </div>
    </>
  );
}
